Low: slapd: cleaned up code a little
I cleaned the code up a little, so here's an updated version.

diff --git a/heartbeat/slapd b/heartbeat/slapd
--- a/heartbeat/slapd
+++ b/heartbeat/slapd
@@ -131,34 +131,34 @@ END
 
 terminate()
 {
-  local ret
   local pid=$1
   local signal=$2
   local recheck=$3
+  local result
 
   if [ -z "$recheck" ]; then
     recheck=1
   fi
 
-  kill -$signal $pid >/dev/null 2>&1; ret=$?
+  kill -$signal $pid >/dev/null 2>&1; result=$?
 
-  if [ $ret -eq 0 ] && [ $recheck -gt 0 ]; then
+  if [ $result -eq 0 ] && [ $recheck -gt 0 ]; then
     # Grant some time for shutdown and recheck n times.
     local i=0
 
-    while [ $ret -eq 0 ] && [ $i -lt $recheck ]; do
-      kill -0 $pid >/dev/null 2>&1; ret=$?
+    while [ $result -eq 0 ] && [ $i -lt $recheck ]; do
+      kill -0 $pid >/dev/null 2>&1; result=$?
       let "i += 1"
 
-      if [ $ret -eq 0 ]; then
+      if [ $result -eq 0 ]; then
         sleep 1
       fi
     done
   else
-    ret=1
+    result=1
   fi
 
-  if [ $ret -ne 0 ]; then
+  if [ $result -ne 0 ]; then
     return 0
   fi
 
@@ -237,17 +237,11 @@ slapd_start()
     options="$options $parameters"
   fi
 
-#  if [ -n "$services" ]; then
-#    options="-h '$services' $options"
-#  fi
-
   if [ -n "$services" ]; then
     $binary -h "$services" $options 2>&1; result=$?
   else
     $binary $options 2>&1; result=$?
   fi
-
-#  $binary $options 2>&1; result=$?
 
   if [ $result -ne 0 ]; then
     ocf_log err "slapd returned error."
@@ -256,7 +250,6 @@ slapd_start()
   fi
 
   ocf_log info "slapd started."
-  sleep 5
 
   return $OCF_SUCCESS
 }
@@ -279,7 +272,7 @@ slapd_stop()
 
   terminate $pid 15 5; result=$?
   if [ $result -ne 0  ]; then
-    ocf_log err "slapd failed to stop. Escalating to KILL"
+    ocf_log err "slapd failed to stop. Escalating to KILL."
 
     terminate $pid 9 5; result=$?
     if [ $result -ne 0 ]; then
